### ISSUE TITLE
"Could not read input file"

### ISSUE THREAD

**Issue by stevage** [TNOCS/minify-geojson#19]
When called without any arguments other than the file name, it throws an exception:

```
$ minify-geojson myfile.geosjon

/Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson.js:29
                        throw new Error('Could not read input file!');
                        ^

Error: Could not read input file!
    at /Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson.js:29:31
    at MinifyGeoJSON.loadFile (/Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson.js:91:20)
    at /Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson.js:27:23
    at Array.forEach (native)
    at new MinifyGeoJSON (/Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson.js:24:21)
    at Object.<anonymous> (/Users/stevebennett/npm/lib/node_modules/minify-geojson/dist/minify-geojson-cli.js:64:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Seems to be ok as long as you pass at least one option like `-k` or `-c 5`

**Comment by erikvullings** [comment]
Good catch

**Comment by erikvullings** [comment]
I've just released a new version, v.1.2, which should fix this issue. It can also deal with much larger files (unless you reproject or want topojson output), as it includes a streaming version of the same algorithms.
