### ISSUE TITLE
Error: Cannot find module '../dist/minify-geojson-cli'

### ISSUE THREAD

**Issue by HuangLiPang** [TNOCS/minify-geojson#25]
How can I fix the error?

```
minify-geojson -b properties original.geojson 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../dist/minify-geojson-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/huanglipang/.nvm/versions/node/v10.16.0/lib/node_modules/minify-geojson/bin/run.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(base) 
```

**Comment by erikvullings** [comment]
Thanks for reporting the issue - after a rename of a file, the link in the `run.js` command was broken. I've published a patch, so please install it using `npm i -g minify-geojson` and try it again.
